language: python

# tell travis to cache ~/.cache/pip
cache: pip

matrix:
  include:
    - python: 3.6
      env: TOXENV=packaging

    - python: 3.6
      env: TOXENV=pep8

    - python: 3.6
      env: TOXENV=black

    - python: 3.5
      env: TOXENV=py35

    - python: 3.6
      env: TOXENV=py36

    - python: 3.7
      env: TOXENV=py37

    - python: 3.8
      env: TOXENV=py38

    - os: osx
      language: generic
      env: TOXENV=py38

    - python: pypy3
      env: TOXENV=pypy3

install:
- ./.travis/install.sh

script:
- tox
