[tox]
envlist = packaging, pep8, black, py{37,38,39,310,311,312,313}-base, py{37,38,39,310,311,312,313}-orjson, pypy3, mypy, isort, coverage
isolated_build = True

[testenv:py]
deps =
    coverage

[testenv:coverage]
; Use this after the other coverage steps have run, to combine and summarize the results
skip_install = True
deps =
    {[testenv:py]deps}

commands =
    coverage combine
    coverage report -m --fail-under 100

[testenv:py{37,38,39,310,311,312,313}-base]
deps =
    {[testenv:py]deps}
commands =
    coverage run -p --source canonicaljson -m unittest

[testenv:py{37,38,39,310,311,312,313}-orjson]
deps =
    {[testenv:py]deps}

extras =
    orjson

commands =
    coverage run -p --source canonicaljson -m unittest

[testenv:packaging]
deps =
    check-manifest
commands = check-manifest

[testenv:pep8]
basepython = python3.7
deps =
    flake8
commands = flake8 src tests

[testenv:isort]
basepython = python3.7
deps =
    isort
commands = isort --check src tests

[testenv:black]
basepython = python3.7
deps =
    black==23.1.0
commands = python -m black --check --diff src tests

[testenv:mypy]
deps =
    mypy==1.0
    types-setuptools==57.4.14
    types-orjson==3.6.0
commands = mypy src tests
